context:
  version: "1.13.12"

package:
  name: sing-box
  version: ${{ version }}

source:
  url: https://github.com/SagerNet/sing-box/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 08f3f7295130b76a60c1cb6565b89da6c4ce98d7bdea8852973a5d2e3c6de3b7

build:
  number: 0
  script:
    - go-licenses save . --save_path library_licenses --ignore github.com/sagernet/
    - if: unix
      then: make VERSION=${{ version }} PREFIX=$PREFIX install
      else: make VERSION=${{ version }} build & cp sing-box.exe %LIBRARY_BIN%

requirements:
  build:
    - ${{ compiler("go-cgo") }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - go-licenses
    - make

tests:
  - script:
      - sing-box --help
      - sing-box version
  - package_contents:
      strict: true
      bin:
        - sing-box

about:
  homepage: https://github.com/SagerNet/sing-box
  summary: The universal proxy platform.
  description: |
    The universal proxy platform
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - library_licenses/
  documentation: https://sing-box.sagernet.org/
  repository: https://github.com/SagerNet/sing-box

extra:
  recipe-maintainers:
    - XhstormR
